version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: yan
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: video
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3305:3306"
    volumes:
      - /path/on/host:/var/lib/mysql